spring.application.name=WebHocTap
server.port=8080
spring.mongodb.uri=mongodb+srv://tsmdoubleliff_db_user:EthernalStrife12@cluster0.hbpgiqg.mongodb.net/webhoctap?retryWrites=true&w=majority
spring.mongodb.database=webhoctap