// Export all pages from here
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as NotFoundPage } from './NotFoundPage'
export * from './ProfilePage'
export { default as ChangePasswordPage } from './ChangePasswordPage'
export { default as CoursesPage } from './CoursesPage'
export { default as CourseDetailPage } from './CourseDetailPage'
export { default as LearningPage } from './LearningPage'
export { QuizPage } from "./QuizPage";
export * from './instructor/InstructorDashboardPage'
export * from './instructor/InstructorCoursesPage'
export * from './instructor/InstructorCreateLessonPage'
export { default as InstructorLivePage } from './instructor/InstructorLivePage'
export { default as FavoritesPage } from './FavoritesPage'
